//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.07 at 04:46:47 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/ecom/soap/api/EcomProducts", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.ecom.soap.api.ecomproducts;
